[package]
name = "cancala"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.7"
# Match prost version with tonic
prost = "0.11"
tokio = { version = "1.19", features = ["rt-multi-thread", "macros"] }
tonic-build = "0.7"

[build-dependencies]
tonic-build = "0.7"
