[package]
name = "cog"
version = "0.1.0"
edition = "2021"

[dependencies]
zmq = "0.10.0"

tonic = "0.7"
prost = "0.10"
tokio = { version = "1.19", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
tonic-build = "0.7"
